name: Bootcamp dar CI

on:
  push:
    branches:
      - main

jobs:
  build_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Load maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Publish package
        run: mvn -B package

      - name: Upload jar file as artifact
        uses: actions/upload-artifact@v1
        with:
          name: jar-artifact
          path: target/MyTasks-0.0.1-SNAPSHOT.jar
  build_push_dev_image:
    runs-on: ubuntu-latest
    needs: build_tests
    name: Build and Push image to ECR
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download jar build artifact
        uses: actions/download-artifact@v1
        with:
          name: jar-artifact
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        run: |
          mkdir -p target
          mv jar-artifact/* target/

          docker build -t sergiohas/dar_bootcamp:latest .
          docker push sergiohas/dar_bootcamp:latest
